In [1]:
a=[1,2,3,4,5]
b=[10,11,12,13,14]

In [2]:
a+b

[1, 2, 3, 4, 5, 10, 11, 12, 13, 14]

In [3]:
result=[]
for first, second in zip(a,b):
    result.append(first+second)

In [4]:
result

[11, 13, 15, 17, 19]

In [5]:
import numpy as np

In [6]:
a=np.array([1,2,3,4,5])

In [7]:
a

array([1, 2, 3, 4, 5])

In [8]:
type(a)

numpy.ndarray

In [9]:
a.dtype

dtype('int32')

In [20]:
f=np.array([1.2,1.7,4.9,6.7,8.9])
f.dtype

dtype('float64')

In [11]:
a[0]

1

In [12]:
a[0]=10

In [13]:
a

array([10,  2,  3,  4,  5])

In [14]:
a.ndim

1

In [15]:
a.shape

(5,)

In [16]:
a.size

5

In [22]:
a+f

array([11.2,  3.7,  7.9, 10.7, 13.9])

In [18]:
a.size

5

In [21]:
f.size

5

In [23]:
a*f

array([12. ,  3.4, 14.7, 26.8, 44.5])

In [24]:
a/f

array([8.33333333, 1.17647059, 0.6122449 , 0.59701493, 0.56179775])

In [25]:
f**a

array([6.19173642e+00, 2.89000000e+00, 1.17649000e+02, 2.01511210e+03,
       5.58405945e+04])

In [26]:
a

array([10,  2,  3,  4,  5])

In [27]:
a*10

array([100,  20,  30,  40,  50])

In [28]:
# Universal functions
np.sin(a)

array([-0.54402111,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [30]:
aa=np.array([[0,1,2,3],[10,11,12,13]])
aa

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [31]:
aa.shape

(2, 4)

In [32]:
aa.size

8

In [33]:
aa.ndim

2

In [34]:
aa[1][3]

13

In [35]:
aa[1][3]=-1

In [36]:
aa

array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

# Slicing

In [37]:
b=np.array([10,11,12,13,14])

In [38]:
b[1:3]

array([11, 12])

In [39]:
b[1:-2]

array([11, 12])

In [40]:
b[-4:3]

array([11, 12])

In [41]:
b[:3]

array([10, 11, 12])

In [42]:
b[-2:]

array([13, 14])

In [43]:
b[::2]

array([10, 12, 14])