In [1]:
import numpy as np

In [2]:
import array

In [3]:
# Create an array
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [5]:
np.array([1,2,3,4,5,"kul", 4+8j])

array(['1', '2', '3', '4', '5', 'kul', '(4+8j)'], dtype='<U64')

In [6]:
np.array([1,2,3,4,5,6.0])

array([1., 2., 3., 4., 5., 6.])

In [7]:
np.array([[1,3],[3,4]])

array([[1, 3],
       [3, 4]])

In [11]:
#2D array
np.array([[1,3],[4,6],[6,8]])

array([[1, 3],
       [4, 6],
       [6, 8]])

In [12]:
np.array([[1,3],[6,8],[5,6,7]])

C:\Users\kulki\AppData\Local\Temp\ipykernel_12940\1550468787.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3],[6,8],[5,6,7]])


array([list([1, 3]), list([6, 8]), list([5, 6, 7])], dtype=object)

In [13]:
#3D array
np.array([[[1,3],[4,5]],[[2,5],[5,6]]])

array([[[1, 3],
        [4, 5]],

       [[2, 5],
        [5, 6]]])

In [14]:
np.array([1,2,3,], ndmin=3)

array([[[1, 2, 3]]])

In [16]:
np.array([1,2,3], ndmin=8)

array([[[[[[[[1, 2, 3]]]]]]]])

In [17]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [19]:
np.array([(1,2),(4,5)])# we can keep data as a list or tuple

array([[1, 2],
       [4, 5]])

In [25]:
arr=np.array([(1,2),(3,4)], dtype=[("a","<i2"),("b","<i8")])
arr

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [22]:
type(arr[0][0])

numpy.int16

In [23]:
type(arr[0][1])

numpy.int64

In [26]:
type(arr[1][1])

numpy.int64

In [27]:
arr=np.array([[1,3],[3,5]])

In [29]:
arr

array([[1, 3],
       [3, 5]])

In [30]:
arr[1][1]

5

In [31]:
arr[0]

array([1, 3])

In [32]:
arr[1]

array([3, 5])

# Create matrix

In [43]:

mat=np.mat(arr)

In [36]:
np.matrix(arr)# create matrix

matrix([[1, 3],
        [3, 5]])

In [37]:
l=[3,4,5,6,7]

# conert list into array


In [39]:
np.array(l)

array([3, 4, 5, 6, 7])

In [40]:
np.asarray(l)

array([3, 4, 5, 6, 7])

In [42]:
np.asanyarray(l)

array([3, 4, 5, 6, 7])

In [44]:
np.asanyarray(mat)

matrix([[1, 3],
        [3, 5]])

In [52]:

"""
by default convert matrix into array. So asarray  everything will convert into array, asanyarry first will try to observe
wheather my data type is available in a form of array or not and if its naot available in a form of array
"""
np.asarray(mat)

array([[1, 3],
       [3, 5]])

In [51]:
np.asarray(mat)

array([[1, 3],
       [3, 5]])

In [48]:
issubclass(np.matrix, np.ndarray)

True

In [49]:
issubclass(np.ndarray, np.matrix)

False

# Concept of deep and sollow copy

In [61]:
arr

array([[67,  3],
       [ 3,  5]])

In [69]:
a=arr# sollow copy
a

array([[67,  3],
       [ 3,  5]])

In [70]:
#deep copy
b=np.copy(arr)# b is not reflecting any changes if wee assign in an original array, it will create a new place in an array
b

array([[67,  3],
       [ 3,  5]])

In [64]:
arr[0][0]=67

In [65]:
arr

array([[67,  3],
       [ 3,  5]])

In [66]:
a

array([[67,  3],
       [ 3,  5]])

In [67]:
b

array([[67,  3],
       [ 3,  5]])

In [71]:
arr[0:10]

array([[67,  3],
       [ 3,  5]])

In [72]:
arr[-1]

array([3, 5])

In [73]:
arr[-2]

array([67,  3])

In [75]:
np.fromfunction(lambda i,j :i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [78]:
np.fromfunction(lambda i,j: i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [80]:
np.fromfunction(lambda i,j: i*j,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [81]:
np.fromfunction(lambda i,j:i/j, (4,4))

C:\Users\kulki\AppData\Local\Temp\ipykernel_12940\383364418.py:1: RuntimeWarning: divide by zero encountered in divide
  np.fromfunction(lambda i,j:i/j, (4,4))
C:\Users\kulki\AppData\Local\Temp\ipykernel_12940\383364418.py:1: RuntimeWarning: invalid value encountered in divide
  np.fromfunction(lambda i,j:i/j, (4,4))


array([[       nan, 0.        , 0.        , 0.        ],
       [       inf, 1.        , 0.5       , 0.33333333],
       [       inf, 2.        , 1.        , 0.66666667],
       [       inf, 3.        , 1.5       , 1.        ]])

# Creating a  generator

In [84]:
(i*i for i in range(5))

<generator object <genexpr> at 0x0000028C462059E0>

In [85]:
[i*i for i in range(5)]

[0, 1, 4, 9, 16]

In [88]:
def test(x):#
    """
    yield->will help you out to create a function which is having behaviour of a generator
    """
    yield x

In [89]:
test(5)

<generator object test at 0x0000028C4624F430>

# Creating data from Generator

In [95]:
gen=(i*i for i in range(5))

In [91]:
gen

<generator object <genexpr> at 0x0000028C4624F740>

In [92]:
np.fromiter(gen, dtype=int)

array([ 0,  1,  4,  9, 16])

In [93]:
np.fromiter(range(5), dtype=int)

array([0, 1, 2, 3, 4])

In [96]:
for i in gen:
    print(i)

0
1
4
9
16


# Generate data from string

In [97]:
np.fromstring('1,2,3,4,5,6', sep=',')

array([1., 2., 3., 4., 5., 6.])

In [98]:
np.fromstring('1,2,3,4,5',sep=',', dtype=int)

array([1, 2, 3, 4, 5])

In [99]:
l=[3,4,5,6,7,8]


In [101]:
arr=np.array(l)

In [102]:
arr1=[[1,2,3,4],[2,3,4,5],[3,4,5,6]]

In [103]:
type(arr)

numpy.ndarray

In [104]:
arr1

[[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6]]

In [105]:
arr2=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])

In [106]:
arr2

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [107]:
arr2.ndim

2

In [108]:
arr2.size

12

In [109]:
arr2.shape

(3, 4)

In [110]:
arr2.dtype

dtype('int32')

In [111]:
arr

array([3, 4, 5, 6, 7, 8])

In [112]:
arr.ndim

1

In [113]:
arr.shape

(6,)

In [115]:
arr3=np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])
arr3

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [116]:
arr3.size

16

In [117]:
arr3.ndim

3

In [118]:
arr3.shape

(2, 2, 4)

In [119]:
#1.18-3.08
arr4=np.array([[[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]]])
arr4

array([[[[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]]]])

In [120]:
arr4.ndim

4

In [121]:
arr4.shape# 

(1, 2, 2, 4)

In [123]:
arr5=np.array([[[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]]])
arr5

array([[[[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]]]])

In [124]:
arr5.ndim

4

In [125]:
arr5.shape

(1, 3, 2, 4)

In [126]:
list(range(5))

[0, 1, 2, 3, 4]

In [127]:
range(6.6)

TypeError: 'float' object cannot be interpreted as an integer

In [128]:
np.arange(6.6)

array([0., 1., 2., 3., 4., 5., 6.])

In [129]:
np.arange(6.6,9,.3)

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

In [130]:
np.arange(6.6,9,-.3)

array([], dtype=float64)

In [131]:
np.arange(9,6.6,-.3)

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [132]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [134]:
np.linspace(3,8)

array([3.        , 3.10204082, 3.20408163, 3.30612245, 3.40816327,
       3.51020408, 3.6122449 , 3.71428571, 3.81632653, 3.91836735,
       4.02040816, 4.12244898, 4.2244898 , 4.32653061, 4.42857143,
       4.53061224, 4.63265306, 4.73469388, 4.83673469, 4.93877551,
       5.04081633, 5.14285714, 5.24489796, 5.34693878, 5.44897959,
       5.55102041, 5.65306122, 5.75510204, 5.85714286, 5.95918367,
       6.06122449, 6.16326531, 6.26530612, 6.36734694, 6.46938776,
       6.57142857, 6.67346939, 6.7755102 , 6.87755102, 6.97959184,
       7.08163265, 7.18367347, 7.28571429, 7.3877551 , 7.48979592,
       7.59183673, 7.69387755, 7.79591837, 7.89795918, 8.        ])

In [135]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [136]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [137]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [138]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [139]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [140]:
np.zeros((2,5,4,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [141]:
np.ones(1)

array([1.])

In [142]:
np.ones(4)

array([1., 1., 1., 1.])

In [143]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [144]:
np.ones((2,3,1))

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [145]:
np.ones((2,3,1))+5

array([[[6.],
        [6.],
        [6.]],

       [[6.],
        [6.],
        [6.]]])

In [146]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [147]:
np.empty((2,3))

array([[6., 6., 6.],
       [6., 6., 6.]])

In [149]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [150]:
np.linspace(2,4,4)

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [153]:
np.linspace(2,4,4, endpoint=False, axis=0)

array([2. , 2.5, 3. , 3.5])

In [154]:
np.linspace(2,3,4, endpoint=False,  axis=1)

AxisError: destination: axis 1 is out of bounds for array of dimension 1

In [158]:
np.linspace([2,3],4, endpoint=False,  axis=1)

array([[2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28, 2.32, 2.36, 2.4 ,
        2.44, 2.48, 2.52, 2.56, 2.6 , 2.64, 2.68, 2.72, 2.76, 2.8 , 2.84,
        2.88, 2.92, 2.96, 3.  , 3.04, 3.08, 3.12, 3.16, 3.2 , 3.24, 3.28,
        3.32, 3.36, 3.4 , 3.44, 3.48, 3.52, 3.56, 3.6 , 3.64, 3.68, 3.72,
        3.76, 3.8 , 3.84, 3.88, 3.92, 3.96],
       [3.  , 3.02, 3.04, 3.06, 3.08, 3.1 , 3.12, 3.14, 3.16, 3.18, 3.2 ,
        3.22, 3.24, 3.26, 3.28, 3.3 , 3.32, 3.34, 3.36, 3.38, 3.4 , 3.42,
        3.44, 3.46, 3.48, 3.5 , 3.52, 3.54, 3.56, 3.58, 3.6 , 3.62, 3.64,
        3.66, 3.68, 3.7 , 3.72, 3.74, 3.76, 3.78, 3.8 , 3.82, 3.84, 3.86,
        3.88, 3.9 , 3.92, 3.94, 3.96, 3.98]])

In [159]:
np.linspace([2,3],4, endpoint=False, axis=0)

array([[2.  , 3.  ],
       [2.04, 3.02],
       [2.08, 3.04],
       [2.12, 3.06],
       [2.16, 3.08],
       [2.2 , 3.1 ],
       [2.24, 3.12],
       [2.28, 3.14],
       [2.32, 3.16],
       [2.36, 3.18],
       [2.4 , 3.2 ],
       [2.44, 3.22],
       [2.48, 3.24],
       [2.52, 3.26],
       [2.56, 3.28],
       [2.6 , 3.3 ],
       [2.64, 3.32],
       [2.68, 3.34],
       [2.72, 3.36],
       [2.76, 3.38],
       [2.8 , 3.4 ],
       [2.84, 3.42],
       [2.88, 3.44],
       [2.92, 3.46],
       [2.96, 3.48],
       [3.  , 3.5 ],
       [3.04, 3.52],
       [3.08, 3.54],
       [3.12, 3.56],
       [3.16, 3.58],
       [3.2 , 3.6 ],
       [3.24, 3.62],
       [3.28, 3.64],
       [3.32, 3.66],
       [3.36, 3.68],
       [3.4 , 3.7 ],
       [3.44, 3.72],
       [3.48, 3.74],
       [3.52, 3.76],
       [3.56, 3.78],
       [3.6 , 3.8 ],
       [3.64, 3.82],
       [3.68, 3.84],
       [3.72, 3.86],
       [3.76, 3.88],
       [3.8 , 3.9 ],
       [3.84, 3.92],
       [3.88,

In [161]:
np.logspace(2,3)

array([ 100.        ,  104.81131342,  109.8541142 ,  115.13953993,
        120.67926406,  126.48552169,  132.57113656,  138.94954944,
        145.63484775,  152.64179672,  159.98587196,  167.68329368,
        175.75106249,  184.20699693,  193.06977289,  202.35896477,
        212.09508879,  222.29964825,  232.99518105,  244.20530945,
        255.95479227,  268.26957953,  281.1768698 ,  294.70517026,
        308.88435965,  323.74575428,  339.32217719,  355.64803062,
        372.75937203,  390.69399371,  409.49150624,  429.19342601,
        449.8432669 ,  471.48663635,  494.17133613,  517.94746792,
        542.86754393,  568.9866029 ,  596.36233166,  625.05519253,
        655.12855686,  686.648845  ,  719.685673  ,  754.31200634,
        790.60432109,  828.64277285,  868.51137375,  910.29817799,
        954.09547635, 1000.        ])

In [164]:
np.logspace([2,3],4, endpoint=False)

array([[ 100.        , 1000.        ],
       [ 109.64781961, 1047.12854805],
       [ 120.22644346, 1096.47819614],
       [ 131.82567386, 1148.1536215 ],
       [ 144.54397707, 1202.26443462],
       [ 158.48931925, 1258.92541179],
       [ 173.78008287, 1318.25673856],
       [ 190.5460718 , 1380.3842646 ],
       [ 208.92961309, 1445.43977075],
       [ 229.08676528, 1513.56124844],
       [ 251.18864315, 1584.89319246],
       [ 275.42287033, 1659.58690744],
       [ 301.99517204, 1737.80082875],
       [ 331.13112148, 1819.70085861],
       [ 363.07805477, 1905.46071796],
       [ 398.10717055, 1995.26231497],
       [ 436.51583224, 2089.29613085],
       [ 478.63009232, 2187.76162395],
       [ 524.80746025, 2290.86765277],
       [ 575.43993734, 2398.83291902],
       [ 630.95734448, 2511.88643151],
       [ 691.83097092, 2630.2679919 ],
       [ 758.57757503, 2754.22870334],
       [ 831.7637711 , 2884.03150313],
       [ 912.01083936, 3019.9517204 ],
       [1000.        , 31

In [165]:
d=np.linspace(4,7,40)
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [166]:
d.ndim

1

In [167]:
d.shape

(40,)

In [168]:
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [170]:
d.reshape(20,2)

array([[4.        , 4.07692308],
       [4.15384615, 4.23076923],
       [4.30769231, 4.38461538],
       [4.46153846, 4.53846154],
       [4.61538462, 4.69230769],
       [4.76923077, 4.84615385],
       [4.92307692, 5.        ],
       [5.07692308, 5.15384615],
       [5.23076923, 5.30769231],
       [5.38461538, 5.46153846],
       [5.53846154, 5.61538462],
       [5.69230769, 5.76923077],
       [5.84615385, 5.92307692],
       [6.        , 6.07692308],
       [6.15384615, 6.23076923],
       [6.30769231, 6.38461538],
       [6.46153846, 6.53846154],
       [6.61538462, 6.69230769],
       [6.76923077, 6.84615385],
       [6.92307692, 7.        ]])

In [171]:
d.reshape(2,1,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [172]:
arr1 = np.random.randint(2,4,(3,3))
arr1 

array([[2, 2, 3],
       [2, 3, 2],
       [3, 2, 3]])

In [173]:
arr2 = np.random.randint(2,4,(3,3))
arr2

array([[2, 2, 3],
       [2, 2, 2],
       [2, 3, 3]])

In [174]:
d=np.linspace(4,7,40)
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [175]:
d.ndim

1

In [176]:
d.shape

(40,)

In [177]:
d.reshape(5,8)

array([[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
        4.38461538, 4.46153846, 4.53846154],
       [4.61538462, 4.69230769, 4.76923077, 4.84615385, 4.92307692,
        5.        , 5.07692308, 5.15384615],
       [5.23076923, 5.30769231, 5.38461538, 5.46153846, 5.53846154,
        5.61538462, 5.69230769, 5.76923077],
       [5.84615385, 5.92307692, 6.        , 6.07692308, 6.15384615,
        6.23076923, 6.30769231, 6.38461538],
       [6.46153846, 6.53846154, 6.61538462, 6.69230769, 6.76923077,
        6.84615385, 6.92307692, 7.        ]])

In [178]:
d.reshape(20,2)

array([[4.        , 4.07692308],
       [4.15384615, 4.23076923],
       [4.30769231, 4.38461538],
       [4.46153846, 4.53846154],
       [4.61538462, 4.69230769],
       [4.76923077, 4.84615385],
       [4.92307692, 5.        ],
       [5.07692308, 5.15384615],
       [5.23076923, 5.30769231],
       [5.38461538, 5.46153846],
       [5.53846154, 5.61538462],
       [5.69230769, 5.76923077],
       [5.84615385, 5.92307692],
       [6.        , 6.07692308],
       [6.15384615, 6.23076923],
       [6.30769231, 6.38461538],
       [6.46153846, 6.53846154],
       [6.61538462, 6.69230769],
       [6.76923077, 6.84615385],
       [6.92307692, 7.        ]])

In [179]:
d.reshape(1,4,10)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [180]:
d.reshape(2,4,10)

ValueError: cannot reshape array of size 40 into shape (2,4,10)

In [181]:
d.reshape(2,4,5)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231],
        [4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308],
        [5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385],
        [5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462],
        [6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [182]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [183]:
np.logspace(1,3,8)

array([  10.        ,   19.30697729,   37.2759372 ,   71.9685673 ,
        138.94954944,  268.26957953,  517.94746792, 1000.        ])

In [184]:
np.random.rand(5)

array([0.69396208, 0.62429785, 0.97610235, 0.36245538, 0.28722286])

In [185]:
np.random.rand(2,2,3)

array([[[0.60931092, 0.01426181, 0.72704286],
        [0.16566976, 0.19323299, 0.81587012]],

       [[0.57999353, 0.34973411, 0.29171532],
        [0.25174875, 0.3947942 , 0.72414965]]])

In [187]:
np.random.rand(3,3,3)

array([[[0.08725468, 0.06595944, 0.01613783],
        [0.73498276, 0.44980802, 0.69402285],
        [0.52932715, 0.70119914, 0.17929468]],

       [[0.29786397, 0.92453244, 0.31347161],
        [0.08372411, 0.79048321, 0.5093182 ],
        [0.29461399, 0.95305651, 0.0032307 ]],

       [[0.66218012, 0.16509544, 0.79542354],
        [0.98277568, 0.46124211, 0.62491992],
        [0.23067532, 0.67705682, 0.13206651]]])

In [188]:
np.random.randint(5,60,(4,4))

array([[27, 43, 42, 28],
       [58, 11, 15, 11],
       [23, 36, 39, 45],
       [21, 32, 41, 58]])

In [190]:
arr=np.random.randint(3,10,(4,4))
arr

array([[9, 4, 4, 3],
       [3, 6, 5, 9],
       [5, 6, 6, 9],
       [7, 6, 4, 6]])

In [191]:
arr.reshape(1,16)

array([[9, 4, 4, 3, 3, 6, 5, 9, 5, 6, 6, 9, 7, 6, 4, 6]])

In [192]:
arr.reshape(2,8)

array([[9, 4, 4, 3, 3, 6, 5, 9],
       [5, 6, 6, 9, 7, 6, 4, 6]])

In [193]:
arr.reshape(16,1)

array([[9],
       [4],
       [4],
       [3],
       [3],
       [6],
       [5],
       [9],
       [5],
       [6],
       [6],
       [9],
       [7],
       [6],
       [4],
       [6]])

In [194]:
arr.reshape(4,4,1)

array([[[9],
        [4],
        [4],
        [3]],

       [[3],
        [6],
        [5],
        [9]],

       [[5],
        [6],
        [6],
        [9]],

       [[7],
        [6],
        [4],
        [6]]])

In [195]:
arr

array([[9, 4, 4, 3],
       [3, 6, 5, 9],
       [5, 6, 6, 9],
       [7, 6, 4, 6]])

In [197]:
arr.max()

9

In [198]:
arr.min()

3

In [199]:
arr

array([[9, 4, 4, 3],
       [3, 6, 5, 9],
       [5, 6, 6, 9],
       [7, 6, 4, 6]])

In [200]:
arr[2:,2:]

array([[6, 9],
       [4, 6]])