In [1]:
import numpy as np
import array

In [3]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [4]:
np.array([1,2,3,4,5,"kzl", 4+5j])

array(['1', '2', '3', '4', '5', 'kzl', '(4+5j)'], dtype='<U64')

In [5]:
np.array([1,2,3,4,5,4.6,9.0])

array([1. , 2. , 3. , 4. , 5. , 4.6, 9. ])

In [6]:
np.array([[1,3],[3,5]])

array([[1, 3],
       [3, 5]])

In [8]:
np.array([[1,3],[3,5],[6,7,9]])

C:\Users\kulki\AppData\Local\Temp\ipykernel_12256\2317029949.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3],[3,5],[6,7,9]])


array([list([1, 3]), list([3, 5]), list([6, 7, 9])], dtype=object)

In [11]:
np.array([[[1,3],[3,4]],[[5,6],[7,8]]])

array([[[1, 3],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [13]:
np.array([2,3], ndmin=4)

array([[[[2, 3]]]])

In [14]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [15]:
np.array([(1,2),(4,5)])

array([[1, 2],
       [4, 5]])

In [17]:
arr=np.array([(1,2),(4,5)], dtype=[("a","<i2"),("b","<i8")])

In [18]:
arr

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [19]:
arr[0][0]

1

In [20]:
type(arr[0][0])

numpy.int16

In [21]:
arr[0][1]

2

In [22]:
type(arr[0][1])

numpy.int64

In [23]:
arr=np.array([[1,2],[3,4]])

In [24]:
arr[1][1]

4

In [25]:
arr[0][1]

2

In [26]:
type(arr[0][0])

numpy.int32

In [32]:
mat=np.mat(arr)

In [28]:
l=[3,4,5,6,7]
np.array(l)

array([3, 4, 5, 6, 7])

In [29]:
np.asarray(l)

array([3, 4, 5, 6, 7])

In [30]:
np.asanyarray(l)

array([3, 4, 5, 6, 7])

In [33]:
np.asanyarray(mat)

matrix([[1, 2],
        [3, 4]])

In [34]:
np.asarray(mat)

array([[1, 2],
       [3, 4]])

In [35]:
issubclass(np.matrix, np.ndarray)

True

In [37]:
issubclass(np.ndarray,np.matrix)

False

In [38]:
arr

array([[1, 2],
       [3, 4]])

In [39]:
a=arr

In [40]:
b=np.copy(arr)

In [41]:
arr[0][0]=45


In [42]:
arr

array([[45,  2],
       [ 3,  4]])

In [43]:
b

array([[1, 2],
       [3, 4]])

In [44]:
a

array([[45,  2],
       [ 3,  4]])

In [45]:
arr[0:10]

array([[45,  2],
       [ 3,  4]])

In [46]:
arr[1]

array([3, 4])

In [47]:
for i in arr:
    print(i)

[45  2]
[3 4]


In [48]:
np.fromfunction(lambda i,j:i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [49]:
type(np.fromfunction(lambda i,j:i==j,(4,4)))

numpy.ndarray

In [50]:
np.fromfunction(lambda x,y: x*y, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [51]:
np.fromfunction(lambda x,y:x/y,(3,3))

C:\Users\kulki\AppData\Local\Temp\ipykernel_12256\898995514.py:1: RuntimeWarning: divide by zero encountered in divide
  np.fromfunction(lambda x,y:x/y,(3,3))
C:\Users\kulki\AppData\Local\Temp\ipykernel_12256\898995514.py:1: RuntimeWarning: invalid value encountered in divide
  np.fromfunction(lambda x,y:x/y,(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [54]:
(i*i for i in range(5))
    

<generator object <genexpr> at 0x00000195E1449E40>

In [55]:
[i*i for i in range(5)]

[0, 1, 4, 9, 16]

In [56]:
def test(x):
    yield x# create a generator
    

In [57]:
test(5)

<generator object test at 0x00000195E1455190>

In [63]:
gen=(i*i for i in range(5))

In [59]:
gen

<generator object <genexpr> at 0x00000195E1455350>

In [60]:
np.fromiter(gen,dtype=int)

array([ 0,  1,  4,  9, 16])

In [61]:
np.fromiter(range(5), dtype=int)

array([0, 1, 2, 3, 4])

In [64]:
for i in gen:
    print(i)

0
1
4
9
16


In [65]:
np.fromstring('1,2,3,4,5', sep=',', dtype=int)

array([1, 2, 3, 4, 5])

In [67]:
np.fromstring("234 345 567", sep=" ", dtype=int)

array([234, 345, 567])

In [68]:
np.fromstring("234,456,567", sep=",", dtype=complex)

array([234.+0.j, 456.+0.j, 567.+0.j])

In [70]:
l=[3,4,5,6,7,8]
arr=np.array(l)

In [74]:
arr1=np.array([[1,2,3,4],[2,3,4,5],[4,5,6,7]])

In [75]:
type(arr)

numpy.ndarray

In [78]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [77]:
arr1.ndim

2

In [79]:
arr1.size

12

In [80]:
arr1.shape

(3, 4)

In [81]:
arr1.dtype

dtype('int32')

In [82]:
arr.size

6

In [83]:
arr.shape

(6,)

In [86]:
arr2=np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])
arr2

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [87]:
arr2.size

16

In [88]:
arr2.ndim

3

In [89]:
arr2.shape

(2, 2, 4)