In [1]:
import numpy as np

In [2]:
import array

In [3]:
# Create an array
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [5]:
np.array([1,2,3,4,5,"kul", 4+8j])

array(['1', '2', '3', '4', '5', 'kul', '(4+8j)'], dtype='<U64')

In [6]:
np.array([1,2,3,4,5,6.0])

array([1., 2., 3., 4., 5., 6.])

In [7]:
np.array([[1,3],[3,4]])

array([[1, 3],
       [3, 4]])

In [11]:
#2D array
np.array([[1,3],[4,6],[6,8]])

array([[1, 3],
       [4, 6],
       [6, 8]])

In [12]:
np.array([[1,3],[6,8],[5,6,7]])

C:\Users\kulki\AppData\Local\Temp\ipykernel_12940\1550468787.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3],[6,8],[5,6,7]])


array([list([1, 3]), list([6, 8]), list([5, 6, 7])], dtype=object)

In [13]:
#3D array
np.array([[[1,3],[4,5]],[[2,5],[5,6]]])

array([[[1, 3],
        [4, 5]],

       [[2, 5],
        [5, 6]]])

In [14]:
np.array([1,2,3,], ndmin=3)

array([[[1, 2, 3]]])

In [16]:
np.array([1,2,3], ndmin=8)

array([[[[[[[[1, 2, 3]]]]]]]])

In [17]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [19]:
np.array([(1,2),(4,5)])# we can keep data as a list or tuple

array([[1, 2],
       [4, 5]])

In [25]:
arr=np.array([(1,2),(3,4)], dtype=[("a","<i2"),("b","<i8")])
arr

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [22]:
type(arr[0][0])

numpy.int16

In [23]:
type(arr[0][1])

numpy.int64

In [26]:
type(arr[1][1])

numpy.int64

In [27]:
arr=np.array([[1,3],[3,5]])

In [29]:
arr

array([[1, 3],
       [3, 5]])

In [30]:
arr[1][1]

5

In [31]:
arr[0]

array([1, 3])

In [32]:
arr[1]

array([3, 5])

# Create matrix

In [43]:

mat=np.mat(arr)

In [36]:
np.matrix(arr)# create matrix

matrix([[1, 3],
        [3, 5]])

In [37]:
l=[3,4,5,6,7]

# conert list into array


In [39]:
np.array(l)

array([3, 4, 5, 6, 7])

In [40]:
np.asarray(l)

array([3, 4, 5, 6, 7])

In [42]:
np.asanyarray(l)

array([3, 4, 5, 6, 7])

In [44]:
np.asanyarray(mat)

matrix([[1, 3],
        [3, 5]])

In [52]:

"""
by default convert matrix into array. So asarray  everything will convert into array, asanyarry first will try to observe
wheather my data type is available in a form of array or not and if its naot available in a form of array
"""
np.asarray(mat)

array([[1, 3],
       [3, 5]])

In [51]:
np.asarray(mat)

array([[1, 3],
       [3, 5]])

In [48]:
issubclass(np.matrix, np.ndarray)

True

In [49]:
issubclass(np.ndarray, np.matrix)

False

# Concept of deep and sollow copy

In [61]:
arr

array([[67,  3],
       [ 3,  5]])

In [69]:
a=arr# sollow copy
a

array([[67,  3],
       [ 3,  5]])

In [70]:
#deep copy
b=np.copy(arr)# b is not reflecting any changes if wee assign in an original array, it will create a new place in an array
b

array([[67,  3],
       [ 3,  5]])

In [64]:
arr[0][0]=67

In [65]:
arr

array([[67,  3],
       [ 3,  5]])

In [66]:
a

array([[67,  3],
       [ 3,  5]])

In [67]:
b

array([[67,  3],
       [ 3,  5]])

In [71]:
arr[0:10]

array([[67,  3],
       [ 3,  5]])

In [72]:
arr[-1]

array([3, 5])

In [73]:
arr[-2]

array([67,  3])

In [75]:
np.fromfunction(lambda i,j :i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [78]:
np.fromfunction(lambda i,j: i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [80]:
np.fromfunction(lambda i,j: i*j,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [81]:
np.fromfunction(lambda i,j:i/j, (4,4))

C:\Users\kulki\AppData\Local\Temp\ipykernel_12940\383364418.py:1: RuntimeWarning: divide by zero encountered in divide
  np.fromfunction(lambda i,j:i/j, (4,4))
C:\Users\kulki\AppData\Local\Temp\ipykernel_12940\383364418.py:1: RuntimeWarning: invalid value encountered in divide
  np.fromfunction(lambda i,j:i/j, (4,4))


array([[       nan, 0.        , 0.        , 0.        ],
       [       inf, 1.        , 0.5       , 0.33333333],
       [       inf, 2.        , 1.        , 0.66666667],
       [       inf, 3.        , 1.5       , 1.        ]])

# Creating a  generator

In [84]:
(i*i for i in range(5))

<generator object <genexpr> at 0x0000028C462059E0>

In [85]:
[i*i for i in range(5)]

[0, 1, 4, 9, 16]

In [88]:
def test(x):#
    """
    yield->will help you out to create a function which is having behaviour of a generator
    """
    yield x

In [89]:
test(5)

<generator object test at 0x0000028C4624F430>

# Creating data from Generator

In [95]:
gen=(i*i for i in range(5))

In [91]:
gen

<generator object <genexpr> at 0x0000028C4624F740>

In [92]:
np.fromiter(gen, dtype=int)

array([ 0,  1,  4,  9, 16])

In [93]:
np.fromiter(range(5), dtype=int)

array([0, 1, 2, 3, 4])

In [96]:
for i in gen:
    print(i)

0
1
4
9
16


# Generate data from string

In [97]:
np.fromstring('1,2,3,4,5,6', sep=',')

array([1., 2., 3., 4., 5., 6.])

In [98]:
np.fromstring('1,2,3,4,5',sep=',', dtype=int)

array([1, 2, 3, 4, 5])

In [99]:
l=[3,4,5,6,7,8]


In [101]:
arr=np.array(l)

In [102]:
arr1=[[1,2,3,4],[2,3,4,5],[3,4,5,6]]

In [103]:
type(arr)

numpy.ndarray

In [104]:
arr1

[[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6]]

In [105]:
arr2=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])

In [106]:
arr2

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [107]:
arr2.ndim

2

In [108]:
arr2.size

12

In [109]:
arr2.shape

(3, 4)

In [110]:
arr2.dtype

dtype('int32')

In [111]:
arr

array([3, 4, 5, 6, 7, 8])

In [112]:
arr.ndim

1

In [113]:
arr.shape

(6,)

In [115]:
arr3=np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])
arr3

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [116]:
arr3.size

16

In [117]:
arr3.ndim

3

In [118]:
arr3.shape

(2, 2, 4)

In [119]:
#1.18-3.08
arr4=np.array([[[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]]])
arr4

array([[[[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]]]])

In [120]:
arr4.ndim

4

In [121]:
arr4.shape# 

(1, 2, 2, 4)

In [123]:
arr5=np.array([[[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]]])
arr5

array([[[[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]]]])

In [124]:
arr5.ndim

4

In [125]:
arr5.shape

(1, 3, 2, 4)

In [126]:
list(range(5))

[0, 1, 2, 3, 4]

In [127]:
range(6.6)

TypeError: 'float' object cannot be interpreted as an integer

In [128]:
np.arange(6.6)

array([0., 1., 2., 3., 4., 5., 6.])

In [129]:
np.arange(6.6,9,.3)

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

In [130]:
np.arange(6.6,9,-.3)

array([], dtype=float64)

In [131]:
np.arange(9,6.6,-.3)

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [132]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [134]:
np.linspace(3,8)

array([3.        , 3.10204082, 3.20408163, 3.30612245, 3.40816327,
       3.51020408, 3.6122449 , 3.71428571, 3.81632653, 3.91836735,
       4.02040816, 4.12244898, 4.2244898 , 4.32653061, 4.42857143,
       4.53061224, 4.63265306, 4.73469388, 4.83673469, 4.93877551,
       5.04081633, 5.14285714, 5.24489796, 5.34693878, 5.44897959,
       5.55102041, 5.65306122, 5.75510204, 5.85714286, 5.95918367,
       6.06122449, 6.16326531, 6.26530612, 6.36734694, 6.46938776,
       6.57142857, 6.67346939, 6.7755102 , 6.87755102, 6.97959184,
       7.08163265, 7.18367347, 7.28571429, 7.3877551 , 7.48979592,
       7.59183673, 7.69387755, 7.79591837, 7.89795918, 8.        ])

In [135]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [136]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [137]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [138]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [139]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [140]:
np.zeros((2,5,4,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])