# Array

In [3]:
import numpy as np

In [2]:
a=np.array([1,4,5,8])
a

array([1, 4, 5, 8])

In [3]:
a=np.array([1,4,5,8], float)
a

array([1., 4., 5., 8.])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.dtype

dtype('float64')

In [6]:
a[:2]

array([1., 4.])

In [7]:
a[3]

8.0

In [8]:
a[0]=5

In [9]:
a

array([5., 4., 5., 8.])

# Multidimensional Array

In [10]:
b=np.array([[1,2,3],[4,5,6]], float)
b

array([[1., 2., 3.],
       [4., 5., 6.]])

# Array Slicing

In [11]:
b[0][0]

1.0

In [12]:
b[1][1]

5.0

In [13]:
b[1:]

array([[4., 5., 6.]])

In [14]:
b[1,:]

array([4., 5., 6.])

In [15]:
b[0,:]

array([1., 2., 3.])

In [17]:
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [16]:
b[:,2]

array([3., 6.])

In [19]:
b[:,1]

array([2., 5.])

In [20]:
b[:,0]

array([1., 4.])

In [25]:
b[0]

array([1., 2., 3.])

In [26]:
b[1]

array([4., 5., 6.])

In [27]:
b[-1]

array([4., 5., 6.])

In [28]:
b[-2]

array([1., 2., 3.])

In [29]:
b[-1:,-2:]

array([[5., 6.]])

In [30]:
b.shape

(2, 3)

In [31]:
2 in b

True

In [32]:
b[1:]

array([[4., 5., 6.]])

In [33]:
b[1,:]

array([4., 5., 6.])

In [35]:
b[0:1]

array([[1., 2., 3.]])

In [36]:
b[0,:]

array([1., 2., 3.])

In [37]:
b[:1]

array([[1., 2., 3.]])

In [38]:
b[:,0]

array([1., 4.])

In [39]:
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [40]:
b[:,2]

array([3., 6.])

In [41]:
b[:,1]

array([2., 5.])

In [43]:
b[0,:2]

array([1., 2.])

In [44]:
b[1,:2]

array([4., 5.])

In [45]:
c=np.array(range(10), float)
c

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [47]:
c=c.reshape(2,5)
c

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [48]:
c=c.reshape(5,2)
c

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [49]:
c

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [50]:
c[1:2]

array([[2., 3.]])

In [51]:
c[:,1]

array([1., 3., 5., 7., 9.])

In [52]:
c[:,0]

array([0., 2., 4., 6., 8.])

In [54]:
c[4][1]

9.0

In [4]:
from numpy import *

In [5]:
# convert to string
a=array([1,2,3], float)
s=a.tostring()
s

C:\Users\kulki\AppData\Local\Temp\ipykernel_12504\2593108022.py:3: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  s=a.tostring()


b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'

In [7]:
np.fromstring(s)

C:\Users\kulki\AppData\Local\Temp\ipykernel_12504\4042211205.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  np.fromstring(s)


array([1., 2., 3.])

In [8]:
a=np.array(range(10), float)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [9]:
a=a.reshape((5,2))
a

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [10]:
b=np.array([1,2,3], float)
b

array([1., 2., 3.])

In [12]:
c=np.copy(b)
c

array([1., 2., 3.])

In [13]:
b

array([1., 2., 3.])

In [14]:
c

array([1., 2., 3.])

In [15]:
b[0]=5

In [16]:
b

array([5., 2., 3.])

In [17]:
c

array([1., 2., 3.])

In [18]:
d=np.array([1,2,3], float)
d

array([1., 2., 3.])

In [19]:
d.tolist()

[1.0, 2.0, 3.0]

In [20]:
d

array([1., 2., 3.])

In [21]:
e=list(d)

In [22]:
e

[1.0, 2.0, 3.0]

In [23]:
a=array([1,2,3],float)
a

array([1., 2., 3.])

In [25]:
s=a.tostring()

C:\Users\kulki\AppData\Local\Temp\ipykernel_12504\3374921192.py:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  s=a.tostring()


In [26]:
s

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'

In [27]:
np.fromstring(s)

C:\Users\kulki\AppData\Local\Temp\ipykernel_12504\4042211205.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  np.fromstring(s)


array([1., 2., 3.])

In [28]:
a=np.array([1,2,3], float)
a

array([1., 2., 3.])

In [29]:
a.fill(0)

In [30]:
a

array([0., 0., 0.])

In [31]:
a

array([0., 0., 0.])

In [32]:
a=np.array(range(6), float).reshape(2,3)
a

array([[0., 1., 2.],
       [3., 4., 5.]])

In [33]:
a.T

array([[0., 3.],
       [1., 4.],
       [2., 5.]])

In [34]:
a=np.array([[1,2,3],[4,5,6]], float)
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [35]:
a.flatten()

array([1., 2., 3., 4., 5., 6.])

In [36]:
a=np.array([1,2,3], float)
b=np.array([4,5,6], float)
c=np.array([7,8,9], float)

In [38]:
np.concatenate((a,b,c))

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [43]:
np.concatenate(((a,b,c)),axis=0)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [46]:
a=np.array([[1,2],[3,4]], float)
b=np.array([[5,6],[7,8]], float)
np.concatenate((a,b))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [47]:
np.concatenate((a,b),axis=0)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [48]:
np.concatenate((a,b), axis=1)

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

In [49]:
a=np.array([1,2,3], float)
a

array([1., 2., 3.])

In [50]:
a[:,np.newaxis]

array([[1.],
       [2.],
       [3.]])

In [51]:
a[np.newaxis,:]

array([[1., 2., 3.]])

In [52]:
a[:,np.newaxis].shape

(3, 1)

# Other way to create an array

In [53]:
np.arange(5,dtype=float)

array([0., 1., 2., 3., 4.])

In [54]:
np.arange(1,6,2, dtype=int)

array([1, 3, 5])

In [56]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [57]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [58]:
a=np.array([[1,2,3],[4,5,6]], float)

In [60]:
np.zeros_like(a)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
np.ones_like(a)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [62]:
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [63]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Array Iteration

In [64]:
a=np.array([1,2,3,4])
for i in a:
    print(i)

1
2
3
4


In [68]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]], float)
for i in a:
    print(i)

[1. 2. 3.]
[4. 5. 6.]
[7. 8. 9.]


In [69]:
for (x,y,z) in a:
    print(x*y*z)

6.0
120.0
504.0


In [70]:
# Basic array operations
a=np.array([2,4,3], float)

In [71]:
a.sum()

9.0

In [72]:
a.prod()

24.0

In [75]:
a=np.array([2,1,9], float)
a.mean()

4.0

In [76]:
a.var()

12.666666666666666

In [77]:
a.std()

3.559026084010437

In [78]:
a=np.array([[3,4,5][6,7,8]],float)
a.argmin()

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\kulki\AppData\Local\Temp\ipykernel_12504\3396443095.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a=np.array([[3,4,5][6,7,8]],float)
C:\Users\kulki\AppData\Local\Temp\ipykernel_12504\3396443095.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a=np.array([[3,4,5][6,7,8]],float)
C:\Users\kulki\AppData\Local\Temp\ipykernel_12504\3396443095.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a=np.array([[3,4,5][6,7,8]],float)


TypeError: list indices must be integers or slices, not tuple