In [1]:
import numpy as np

In [2]:
import array

In [3]:
# Create an array
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [5]:
np.array([1,2,3,4,5,"kul", 4+8j])

array(['1', '2', '3', '4', '5', 'kul', '(4+8j)'], dtype='<U64')

In [6]:
np.array([1,2,3,4,5,6.0])

array([1., 2., 3., 4., 5., 6.])

In [7]:
np.array([[1,3],[3,4]])

array([[1, 3],
       [3, 4]])

In [11]:
#2D array
np.array([[1,3],[4,6],[6,8]])

array([[1, 3],
       [4, 6],
       [6, 8]])

In [12]:
np.array([[1,3],[6,8],[5,6,7]])

C:\Users\kulki\AppData\Local\Temp\ipykernel_12940\1550468787.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3],[6,8],[5,6,7]])


array([list([1, 3]), list([6, 8]), list([5, 6, 7])], dtype=object)

In [13]:
#3D array
np.array([[[1,3],[4,5]],[[2,5],[5,6]]])

array([[[1, 3],
        [4, 5]],

       [[2, 5],
        [5, 6]]])

In [14]:
np.array([1,2,3,], ndmin=3)

array([[[1, 2, 3]]])

In [16]:
np.array([1,2,3], ndmin=8)

array([[[[[[[[1, 2, 3]]]]]]]])

In [17]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [19]:
np.array([(1,2),(4,5)])# we can keep data as a list or tuple

array([[1, 2],
       [4, 5]])

In [25]:
arr=np.array([(1,2),(3,4)], dtype=[("a","<i2"),("b","<i8")])
arr

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [22]:
type(arr[0][0])

numpy.int16

In [23]:
type(arr[0][1])

numpy.int64

In [26]:
type(arr[1][1])

numpy.int64

In [27]:
arr=np.array([[1,3],[3,5]])

In [29]:
arr

array([[1, 3],
       [3, 5]])

In [30]:
arr[1][1]

5

In [31]:
arr[0]

array([1, 3])

In [32]:
arr[1]

array([3, 5])

# Create matrix

In [43]:

mat=np.mat(arr)

In [36]:
np.matrix(arr)# create matrix

matrix([[1, 3],
        [3, 5]])

In [37]:
l=[3,4,5,6,7]

# conert list into array


In [39]:
np.array(l)

array([3, 4, 5, 6, 7])

In [40]:
np.asarray(l)

array([3, 4, 5, 6, 7])

In [42]:
np.asanyarray(l)

array([3, 4, 5, 6, 7])

In [44]:
np.asanyarray(mat)

matrix([[1, 3],
        [3, 5]])

In [52]:

"""
by default convert matrix into array. So asarray  everything will convert into array, asanyarry first will try to observe
wheather my data type is available in a form of array or not and if its naot available in a form of array
"""
np.asarray(mat)

array([[1, 3],
       [3, 5]])

In [51]:
np.asarray(mat)

array([[1, 3],
       [3, 5]])

In [48]:
issubclass(np.matrix, np.ndarray)

True

In [49]:
issubclass(np.ndarray, np.matrix)

False

# Concept of deep and sollow copy

In [61]:
arr

array([[67,  3],
       [ 3,  5]])

In [69]:
a=arr# sollow copy
a

array([[67,  3],
       [ 3,  5]])

In [70]:
#deep copy
b=np.copy(arr)# b is not reflecting any changes if wee assign in an original array, it will create a new place in an array
b

array([[67,  3],
       [ 3,  5]])

In [64]:
arr[0][0]=67

In [65]:
arr

array([[67,  3],
       [ 3,  5]])

In [66]:
a

array([[67,  3],
       [ 3,  5]])

In [67]:
b

array([[67,  3],
       [ 3,  5]])

In [71]:
arr[0:10]

array([[67,  3],
       [ 3,  5]])

In [72]:
arr[-1]

array([3, 5])

In [73]:
arr[-2]

array([67,  3])

In [75]:
np.fromfunction(lambda i,j :i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [78]:
np.fromfunction(lambda i,j: i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])