In [1]:
import numpy as np
import array

In [3]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [4]:
np.array([1,2,3,4,5,"kzl", 4+5j])

array(['1', '2', '3', '4', '5', 'kzl', '(4+5j)'], dtype='<U64')

In [5]:
np.array([1,2,3,4,5,4.6,9.0])

array([1. , 2. , 3. , 4. , 5. , 4.6, 9. ])

In [6]:
np.array([[1,3],[3,5]])

array([[1, 3],
       [3, 5]])

In [8]:
np.array([[1,3],[3,5],[6,7,9]])

C:\Users\kulki\AppData\Local\Temp\ipykernel_12256\2317029949.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3],[3,5],[6,7,9]])


array([list([1, 3]), list([3, 5]), list([6, 7, 9])], dtype=object)

In [11]:
np.array([[[1,3],[3,4]],[[5,6],[7,8]]])

array([[[1, 3],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [13]:
np.array([2,3], ndmin=4)

array([[[[2, 3]]]])

In [14]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [15]:
np.array([(1,2),(4,5)])

array([[1, 2],
       [4, 5]])

In [17]:
arr=np.array([(1,2),(4,5)], dtype=[("a","<i2"),("b","<i8")])

In [18]:
arr

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [19]:
arr[0][0]

1

In [20]:
type(arr[0][0])

numpy.int16

In [21]:
arr[0][1]

2

In [22]:
type(arr[0][1])

numpy.int64

In [23]:
arr=np.array([[1,2],[3,4]])

In [24]:
arr[1][1]

4

In [25]:
arr[0][1]

2

In [26]:
type(arr[0][0])

numpy.int32

In [32]:
mat=np.mat(arr)

In [28]:
l=[3,4,5,6,7]
np.array(l)

array([3, 4, 5, 6, 7])

In [29]:
np.asarray(l)

array([3, 4, 5, 6, 7])

In [30]:
np.asanyarray(l)

array([3, 4, 5, 6, 7])

In [33]:
np.asanyarray(mat)

matrix([[1, 2],
        [3, 4]])

In [34]:
np.asarray(mat)

array([[1, 2],
       [3, 4]])

In [35]:
issubclass(np.matrix, np.ndarray)

True

In [37]:
issubclass(np.ndarray,np.matrix)

False

In [38]:
arr

array([[1, 2],
       [3, 4]])

In [39]:
a=arr

In [40]:
b=np.copy(arr)

In [41]:
arr[0][0]=45


In [42]:
arr

array([[45,  2],
       [ 3,  4]])

In [43]:
b

array([[1, 2],
       [3, 4]])

In [44]:
a

array([[45,  2],
       [ 3,  4]])

In [45]:
arr[0:10]

array([[45,  2],
       [ 3,  4]])

In [46]:
arr[1]

array([3, 4])

In [47]:
for i in arr:
    print(i)

[45  2]
[3 4]


In [48]:
np.fromfunction(lambda i,j:i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [49]:
type(np.fromfunction(lambda i,j:i==j,(4,4)))

numpy.ndarray

In [50]:
np.fromfunction(lambda x,y: x*y, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [51]:
np.fromfunction(lambda x,y:x/y,(3,3))

C:\Users\kulki\AppData\Local\Temp\ipykernel_12256\898995514.py:1: RuntimeWarning: divide by zero encountered in divide
  np.fromfunction(lambda x,y:x/y,(3,3))
C:\Users\kulki\AppData\Local\Temp\ipykernel_12256\898995514.py:1: RuntimeWarning: invalid value encountered in divide
  np.fromfunction(lambda x,y:x/y,(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [54]:
(i*i for i in range(5))
    

<generator object <genexpr> at 0x00000195E1449E40>

In [55]:
[i*i for i in range(5)]

[0, 1, 4, 9, 16]

In [56]:
def test(x):
    yield x# create a generator
    

In [57]:
test(5)

<generator object test at 0x00000195E1455190>

In [63]:
gen=(i*i for i in range(5))

In [59]:
gen

<generator object <genexpr> at 0x00000195E1455350>

In [60]:
np.fromiter(gen,dtype=int)

array([ 0,  1,  4,  9, 16])

In [61]:
np.fromiter(range(5), dtype=int)

array([0, 1, 2, 3, 4])

In [64]:
for i in gen:
    print(i)

0
1
4
9
16


In [65]:
np.fromstring('1,2,3,4,5', sep=',', dtype=int)

array([1, 2, 3, 4, 5])

In [67]:
np.fromstring("234 345 567", sep=" ", dtype=int)

array([234, 345, 567])

In [68]:
np.fromstring("234,456,567", sep=",", dtype=complex)

array([234.+0.j, 456.+0.j, 567.+0.j])

In [70]:
l=[3,4,5,6,7,8]
arr=np.array(l)

In [74]:
arr1=np.array([[1,2,3,4],[2,3,4,5],[4,5,6,7]])

In [75]:
type(arr)

numpy.ndarray

In [78]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [77]:
arr1.ndim

2

In [79]:
arr1.size

12

In [80]:
arr1.shape

(3, 4)

In [81]:
arr1.dtype

dtype('int32')

In [82]:
arr.size

6

In [83]:
arr.shape

(6,)

In [86]:
arr2=np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])
arr2

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [87]:
arr2.size

16

In [88]:
arr2.ndim

3

In [89]:
arr2.shape

(2, 2, 4)

In [93]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [94]:
list(np.arange(6.6))

[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0]

In [95]:
np.arange(6.6,9,0.3)

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

In [96]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [97]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [98]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [99]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [100]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [102]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [103]:
np.zeros((3,2,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [104]:
np.zeros((2,5,3,1))

array([[[[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]]])

In [105]:
np.zeros((2,5,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [107]:
np.zeros((2,2,5,3,2))

array([[[[[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]]]],



       [[[[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.],
          [0., 0.]],



In [108]:
np.ones(4)

array([1., 1., 1., 1.])

In [109]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [110]:
np.ones((2,3,1))

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [112]:
np.ones((2,3,1))+4

array([[[5.],
        [5.],
        [5.]],

       [[5.],
        [5.],
        [5.]]])

In [113]:
np.empty(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [114]:
np.empty((2,3))

array([[5., 5., 5.],
       [5., 5., 5.]])

In [115]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [117]:
np.eye(2,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [121]:
np.eye(2,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [122]:
np.eye(4,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [123]:
np.linspace(2,4,4)

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [124]:
np.linspace(2,4,4,endpoint=False)

array([2. , 2.5, 3. , 3.5])

In [125]:
np.linspace(2,4,4, endpoint=False, axis=0)

array([2. , 2.5, 3. , 3.5])

In [126]:
np.linspace(2,4,4, endpoint=False, axis=1)

AxisError: destination: axis 1 is out of bounds for array of dimension 1

In [127]:
np.linspace([1,6],4, endpoint=False, axis=0)

array([[1.  , 6.  ],
       [1.06, 5.96],
       [1.12, 5.92],
       [1.18, 5.88],
       [1.24, 5.84],
       [1.3 , 5.8 ],
       [1.36, 5.76],
       [1.42, 5.72],
       [1.48, 5.68],
       [1.54, 5.64],
       [1.6 , 5.6 ],
       [1.66, 5.56],
       [1.72, 5.52],
       [1.78, 5.48],
       [1.84, 5.44],
       [1.9 , 5.4 ],
       [1.96, 5.36],
       [2.02, 5.32],
       [2.08, 5.28],
       [2.14, 5.24],
       [2.2 , 5.2 ],
       [2.26, 5.16],
       [2.32, 5.12],
       [2.38, 5.08],
       [2.44, 5.04],
       [2.5 , 5.  ],
       [2.56, 4.96],
       [2.62, 4.92],
       [2.68, 4.88],
       [2.74, 4.84],
       [2.8 , 4.8 ],
       [2.86, 4.76],
       [2.92, 4.72],
       [2.98, 4.68],
       [3.04, 4.64],
       [3.1 , 4.6 ],
       [3.16, 4.56],
       [3.22, 4.52],
       [3.28, 4.48],
       [3.34, 4.44],
       [3.4 , 4.4 ],
       [3.46, 4.36],
       [3.52, 4.32],
       [3.58, 4.28],
       [3.64, 4.24],
       [3.7 , 4.2 ],
       [3.76, 4.16],
       [3.82,

In [128]:
np.linspace([1,6],4, endpoint=False, axis=1)

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [6.  , 5.96, 5.92, 5.88, 5.84, 5.8 , 5.76, 5.72, 5.68, 5.64, 5.6 ,
        5.56, 5.52, 5.48, 5.44, 5.4 , 5.36, 5.32, 5.28, 5.24, 5.2 , 5.16,
        5.12, 5.08, 5.04, 5.  , 4.96, 4.92, 4.88, 4.84, 4.8 , 4.76, 4.72,
        4.68, 4.64, 4.6 , 4.56, 4.52, 4.48, 4.44, 4.4 , 4.36, 4.32, 4.28,
        4.24, 4.2 , 4.16, 4.12, 4.08, 4.04]])

In [129]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [130]:
np.logspace([2,3],4)

array([[  100.        ,  1000.        ],
       [  109.8541142 ,  1048.11313415],
       [  120.67926406,  1098.54114199],
       [  132.57113656,  1151.39539933],
       [  145.63484775,  1206.79264064],
       [  159.98587196,  1264.85521686],
       [  175.75106249,  1325.71136559],
       [  193.06977289,  1389.49549437],
       [  212.09508879,  1456.3484775 ],
       [  232.99518105,  1526.41796718],
       [  255.95479227,  1599.85871961],
       [  281.1768698 ,  1676.83293681],
       [  308.88435965,  1757.51062485],
       [  339.32217719,  1842.06996933],
       [  372.75937203,  1930.69772888],
       [  409.49150624,  2023.58964773],
       [  449.8432669 ,  2120.95088792],
       [  494.17133613,  2222.99648253],
       [  542.86754393,  2329.95181052],
       [  596.36233166,  2442.05309455],
       [  655.12855686,  2559.5479227 ],
       [  719.685673  ,  2682.69579528],
       [  790.60432109,  2811.76869797],
       [  868.51137375,  2947.05170255],
       [  954.09

In [133]:
np.logspace([2,3],4, axis=1)

array([[  100.        ,   109.8541142 ,   120.67926406,   132.57113656,
          145.63484775,   159.98587196,   175.75106249,   193.06977289,
          212.09508879,   232.99518105,   255.95479227,   281.1768698 ,
          308.88435965,   339.32217719,   372.75937203,   409.49150624,
          449.8432669 ,   494.17133613,   542.86754393,   596.36233166,
          655.12855686,   719.685673  ,   790.60432109,   868.51137375,
          954.09547635,  1048.11313415,  1151.39539933,  1264.85521686,
         1389.49549437,  1526.41796718,  1676.83293681,  1842.06996933,
         2023.58964773,  2222.99648253,  2442.05309455,  2682.69579528,
         2947.05170255,  3237.45754282,  3556.48030622,  3906.93993705,
         4291.93426013,  4714.86636346,  5179.47467923,  5689.86602902,
         6250.55192527,  6866.48845004,  7543.12006335,  8286.42772855,
         9102.98177992, 10000.        ],
       [ 1000.        ,  1048.11313415,  1098.54114199,  1151.39539933,
         1206.79264064,

In [134]:
np.logspace([2],[3], axis=1)

array([[ 100.        ,  104.81131342,  109.8541142 ,  115.13953993,
         120.67926406,  126.48552169,  132.57113656,  138.94954944,
         145.63484775,  152.64179672,  159.98587196,  167.68329368,
         175.75106249,  184.20699693,  193.06977289,  202.35896477,
         212.09508879,  222.29964825,  232.99518105,  244.20530945,
         255.95479227,  268.26957953,  281.1768698 ,  294.70517026,
         308.88435965,  323.74575428,  339.32217719,  355.64803062,
         372.75937203,  390.69399371,  409.49150624,  429.19342601,
         449.8432669 ,  471.48663635,  494.17133613,  517.94746792,
         542.86754393,  568.9866029 ,  596.36233166,  625.05519253,
         655.12855686,  686.648845  ,  719.685673  ,  754.31200634,
         790.60432109,  828.64277285,  868.51137375,  910.29817799,
         954.09547635, 1000.        ]])

In [135]:
np.logspace([2],[3], axis=0)

array([[ 100.        ],
       [ 104.81131342],
       [ 109.8541142 ],
       [ 115.13953993],
       [ 120.67926406],
       [ 126.48552169],
       [ 132.57113656],
       [ 138.94954944],
       [ 145.63484775],
       [ 152.64179672],
       [ 159.98587196],
       [ 167.68329368],
       [ 175.75106249],
       [ 184.20699693],
       [ 193.06977289],
       [ 202.35896477],
       [ 212.09508879],
       [ 222.29964825],
       [ 232.99518105],
       [ 244.20530945],
       [ 255.95479227],
       [ 268.26957953],
       [ 281.1768698 ],
       [ 294.70517026],
       [ 308.88435965],
       [ 323.74575428],
       [ 339.32217719],
       [ 355.64803062],
       [ 372.75937203],
       [ 390.69399371],
       [ 409.49150624],
       [ 429.19342601],
       [ 449.8432669 ],
       [ 471.48663635],
       [ 494.17133613],
       [ 517.94746792],
       [ 542.86754393],
       [ 568.9866029 ],
       [ 596.36233166],
       [ 625.05519253],
       [ 655.12855686],
       [ 686.648

In [136]:
data=np.linspace(4,7,40)
data

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [139]:
data.ndim

1

In [140]:
data.shape

(40,)

In [141]:
data.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [142]:
data.reshape(20,2)

array([[4.        , 4.07692308],
       [4.15384615, 4.23076923],
       [4.30769231, 4.38461538],
       [4.46153846, 4.53846154],
       [4.61538462, 4.69230769],
       [4.76923077, 4.84615385],
       [4.92307692, 5.        ],
       [5.07692308, 5.15384615],
       [5.23076923, 5.30769231],
       [5.38461538, 5.46153846],
       [5.53846154, 5.61538462],
       [5.69230769, 5.76923077],
       [5.84615385, 5.92307692],
       [6.        , 6.07692308],
       [6.15384615, 6.23076923],
       [6.30769231, 6.38461538],
       [6.46153846, 6.53846154],
       [6.61538462, 6.69230769],
       [6.76923077, 6.84615385],
       [6.92307692, 7.        ]])

In [143]:
data.reshape(2,1,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [146]:
data.reshape(1,2,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [148]:
data.reshape(2,1,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [149]:
np.random.rand(3)

array([0.12050134, 0.62846235, 0.94529983])

In [150]:
np.random.randn(5)# return from a std# std normal distribution->mean=0,std=1,  normal distribution:- mean can be anything, std can be anything

array([-1.715382  ,  1.63063515, -0.25154013, -0.1206089 , -0.20782578])

In [151]:
np.random.randn(2,3)

array([[-1.13504946, -0.58067997, -0.7801604 ],
       [-0.17410663,  0.4099016 ,  0.62266931]])

In [152]:
np.random.randn(3,2,2)

array([[[-0.18069307, -0.040134  ],
        [ 0.52905933,  0.11758586]],

       [[ 0.47856658, -0.33390103],
        [-0.02280774,  0.93923278]],

       [[-0.50621135, -0.16912463],
        [-0.57838947, -0.65065104]]])

In [153]:
np.random.randint(5)

4

In [154]:
np.random.randint(5,10)

6

In [155]:
np.random.randint(5,60,(4,4))

array([[16, 58, 33, 59],
       [35, 13, 27, 39],
       [21,  5, 56, 59],
       [22, 53, 11, 14]])

In [156]:
arr=np.random.randint(3,9,(3,3))

In [157]:
arr

array([[3, 3, 3],
       [7, 4, 7],
       [6, 8, 8]])

In [158]:
arr.reshape(1,9)

array([[3, 3, 3, 7, 4, 7, 6, 8, 8]])

In [159]:
arr.reshape(9,1)

array([[3],
       [3],
       [3],
       [7],
       [4],
       [7],
       [6],
       [8],
       [8]])

In [160]:
arr.reshape(1,1,9)

array([[[3, 3, 3, 7, 4, 7, 6, 8, 8]]])

In [161]:
arr.reshape(3,1,3)

array([[[3, 3, 3]],

       [[7, 4, 7]],

       [[6, 8, 8]]])

In [162]:
arr.reshape(3,3,1)

array([[[3],
        [3],
        [3]],

       [[7],
        [4],
        [7]],

       [[6],
        [8],
        [8]]])

In [163]:
arr.reshape(3,-1)

array([[3, 3, 3],
       [7, 4, 7],
       [6, 8, 8]])

In [164]:
arr.reshape(2,-1)

ValueError: cannot reshape array of size 9 into shape (2,newaxis)

In [166]:
arr.reshape(1,-1)

array([[3, 3, 3, 7, 4, 7, 6, 8, 8]])

In [167]:
arr.max()

8

In [168]:
arr.min()

3

In [170]:
arr=np.random.randint(4,100,(5,5))
arr

array([[45, 63,  6, 86, 59],
       [52, 67, 28, 41, 76],
       [59, 43, 17, 64, 49],
       [70, 55, 35, 62, 78],
       [44, 75, 99, 72, 18]])

In [171]:
arr[3:, 3:]

array([[62, 78],
       [72, 18]])

In [173]:
arr[:,[1,3]]# all the rows and colum 1 and 3

array([[63, 86],
       [67, 41],
       [43, 64],
       [55, 62],
       [75, 72]])

In [174]:
arr[[1,4], :]

array([[52, 67, 28, 41, 76],
       [44, 75, 99, 72, 18]])

In [175]:
arr

array([[45, 63,  6, 86, 59],
       [52, 67, 28, 41, 76],
       [59, 43, 17, 64, 49],
       [70, 55, 35, 62, 78],
       [44, 75, 99, 72, 18]])

In [176]:
arr>10

array([[ True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [177]:
arr[arr>10]

array([45, 63, 86, 59, 52, 67, 28, 41, 76, 59, 43, 17, 64, 49, 70, 55, 35,
       62, 78, 44, 75, 99, 72, 18])